### ISSUE TITLE
C++ Bindings

### ISSUE THREAD

**Issue by tazaraz** [mwlon/pcodec#126]
I know this has already been mentioned in #53, but could you please add c++ bindings? It is akward to manually create bindings to a library which gets updated frequently and which I do not fully understand.

**Comment by mwlon** [comment]
What are you looking to do in C++?

I could make bindings to the `auto_(de)compress` functions, but I'm unlikely to make lower-level bindings soon. I'm not very familiar with C++.

For `q_compress`, [I have a one-sided example](https://github.com/mwlon/pcodec/tree/main/quantile-compression/ffi) if that's helpful.

**Comment by tazaraz** [comment]
I am looking to use the compression library in a project of mine, and as such, so as long as I can have access to the (de)compression functions defined in `standalone/(de)compressor.rs` along with the config options would be very nice. Do those functions differ from the `auto_(de)compress` functions?

As for the example you gave, I'm completely in the dark on what is going on in the `lib.rs` file or what I could do with it: I, in contrast, am unfortunately not familiar with Rust :/

**Comment by mwlon** [comment]
@tazaraz We just started some basic C bindings (under `./pco_c`). At the moment it's only the standalone `auto_(de)compress` functions, so the only config available is compression level. And you need to built the dynamic library with `cargo build --release`. But perhaps this is a starting point for what you were hoping to make?

**Comment by mwlon** [comment]
Closing this since we have https://github.com/mwlon/pcodec/tree/main/pco_c now
