### ISSUE TITLE
Python bindings?

### ISSUE THREAD

**Issue by rabernat** [mwlon/pcodec#128]
Thanks for sharing this exciting new compression codec. :pray:

I'm a maintainer of [numcodecs](https://numcodecs.readthedocs.io/en/stable/), a Python library which attempts to wrap all common numerical compression codecs (e.g. blosc, zstd, lz4, etc.) and present them via a standard interface. Numcodecs is used, for example, by the [Zarr](https://zarr.dev/) library as a compression layer.

We'd love to include pcodec in numcodecs. To do so, we'd need some sort of Python wrapper. This should be straightforward with pyo3. We would be happy to make a PR to accomplish this, but I thought I would first open an issue to see whether this was already on the roadmap. Given the amount of data science that happens in Python, Python bindings would help your work reach a much wider audience.

Thanks again for your generous open source contributions.

**Comment by mwlon** [comment]
@rabernat sounds like a great idea! This is something I've wanted to do, but haven't made an explicit plan to do yet. A PR would certainly be welcome.

Are you thinking of just wrapping the auto_compress/decompress functions or lower level functionality as well?

**Comment by mwlon** [comment]
Having taken a closer look at numcodecs: seems like the public functionality is compressing/decompressing an entire buffer, so the standalone format and auto_* would be a good fit. It would compress/decompress to a numpy array (or something like one), and it would take a config that looks like [ChunkConfig](https://docs.rs/pco/latest/pco/struct.ChunkConfig.html).

Does that all match up with your expectations?

**Comment by rabernat** [comment]
Thanks for the quick reply!

> Are you thinking of just wrapping the auto_compress/decompress functions or lower level functionality as well?

I think that's a fine place to start. From the numcodecs pov, the interface we need is simple: we want to turn numpy arrays into compressed `bytes` and vice versa, ideally with as few memory copies as much as possible. `auto_compress` an `simple_compress` should be fine, since they can accept views into an existing numpy array. They need to allocate a new (unknown size) bytes object, and that's fine.

For `auto_decompress`, the one thing missing is the ability to decompress into an existing buffer. For numcodecs, we will always know the size of the array we are decompressing, and many users of the library will provide an `out` argument: https://github.com/zarr-developers/numcodecs/blob/4896680087d3ff1f959401c51cf5aea0fd56554e/numcodecs/abc.py#L59-L70

But it looks like `auto_decompress` always allocates a new vec for its output:
https://github.com/mwlon/pcodec/blob/2314e329f36684b3f6476f4d69150acc6ac3786b/pco/src/standalone/simple.rs#L64

So we would have to copy the results into `out`. This means we would likely want to use the lower-level interface... or add a new high-level function with this capability.

**Comment by mwlon** [comment]
Aha - in that case, probably best I add a new piece of high level functionality for you to use; I might make an unrelated change to the low level standalone API in the next release.

What is numcodec's intended behavior when the `dest` is too small?

**Comment by djawdjjalodkpsaodkpw** [comment]
sounds like a great idea! This is something I've wanted to do, but haven't made an explicit plan to do yet. A PR would certainly be welcome.

Are you thinking of just wrapping the auto_compress/decompress functions or lower level functionality as well?

**Comment by Hurtknight** [comment]
Having taken a closer look at numcodecs: seems like the public functionality is compressing/decompressing an entire buffer, so the standalone format and auto_* would be a good fit. It would compress/decompress to a numpy array (or something like one), and it would take a config that looks like [ChunkConfig](https://docs.rs/pco/latest/pco/struct.ChunkConfig.html).

Does that all match up with your expectations?

**Comment by rabernat** [comment]
> What is numcodec's intended behavior when the `dest` is too small?

The way we use numcodecs from zarr, that should never happen. We are usually decompressing ND arrays with an a priori known size. It's the user's responsibility to make the buffer the right size: "this buffer must be exactly the right size to store the decoded data."

So the correct behavior if `dest` is too small would be to raise an error.

**Comment by mwlon** [comment]
I've added `pco::standalone::simple_decompress_into` to main, and I'll probably make a 0.1.0 release including it in a couple days.

**Comment by mwlon** [comment]
I just released 0.1.0, so I think you should be unblocked. Looking forward to your PR!

**Comment by rabernat** [comment]
I have a basic working version up here: https://github.com/rabernat/pcodec-python

The way I have approached this to start was to create a tiny standalone crate with dependencies on pco, pyo3, and numpy. This contains:
- [lib.rs](https://github.com/rabernat/pcodec-python/blob/main/src/lib.rs) - the simple glue code to make the pco functions callable from python
- [test_pcodec.py](https://github.com/rabernat/pcodec-python/blob/main/test/test_pcodec.py) - a simple python test

Before making a PR, I thought I would get your feedback on how you'd want to structure this.
- How do you feel about making a new top-level `pco_python` crate in this package? Or would you rather have this embedded in the `pco` crate itself?
- Are you supportive of running the python tests as part of the CI in this repo?
