### ISSUE TITLE
Spec clarification/suggestions

### ISSUE THREAD

**Issue by emkornfield** [mwlon/pcodec#149]
Based on reviewing [the format spec](https://github.com/mwlon/pcodec/blob/main/docs/format.md) from the conversation on Parquet.  I had some comments/suggestions (thanks for the write-up so far):

0.  Consider starting with an overview of the overall encoding/decoding algorithm defining each of the terms in it (it currently focuses mostly on decoding), with examples for each step along the way.
1.  Enumerate valid format versions (I expected this is only zero or 1?)
2. phrasing the second element of chunk metadata (0 or dtype_size] bits, is unclear what this values represents.  It seems like it is only included if `mode != classic`
3. tAns description/definitions (its not clear if there is one well defined algorithm for this or there are several. Links/copies to the canonical algorithm or a description of the algorithm as implemented are necessary I think:
    1. Define latent variables (this might be part of tAns descriptions).
    2. corruption is defined in terms of some of bin weight and tANS size which do not seem to be formally defined.
4. I don't expect this to change but I think it is unfortunate from a parquet inter-op perspective that some terminology is very similar (e.g. Data Page)
5. define "delta encoding order" probably with examples (web search does not seem to turn up any results in the first few hits).
6. Enumerate the non-trivial bijections to uint float.
7. define `machine_epsilon` its not clear if float multiply is working with floating point numbers (if it is it doesn't seem lossless).
8. the per latent variable fields, it doesn't seem like they are guaranteed to be byte aligned (are byte zero padded?)

I might be misunderstanding some aspects of the algorithm and some of these are partially covered and it just might be about reorganizing some of the flow for people new the algorithm.

**Comment by mwlon** [comment]
Thanks for your feedback.

0. As a format description, the goal of the document is only to describe the many->one correspondence from compressed_representation->uncompressed_representation. As with almost any compression algorithm, the mapping from uncompressed_representation->compressed_representation is one->many and is up to the compression algorithm (not the format). The description of formulas is at the bottom.
1. Done.
2. I defined the encoding of "raw" values more clearly now.
3. tANS is a well-known algorithm; added a couple links.
4. I think for the most part it's actually a good thing; at least for data page, the two notions should overlap exactly between Parquet and Pcodec (or else the implementation is bad).
5. [This was already described](https://github.com/mwlon/pcodec/blob/main/docs/format.md#latents---deltas).
6. Added more detail.
7. I've rephrased it in ULPs to be clearer. It is lossless; IEEE multiplication is deterministic.
8. Other than each component's start and end, nothing is guaranteed to be byte-aligned. I'm not sure what you mean by latent variable fields?

**Comment by mwlon** [comment]
Actually, there is a byte alignment after each page's metadata. Added that to the doc.

**Comment by emkornfield** [comment]
> As a format description, the goal of the document is only to describe the many->one correspondence from compressed_representation->uncompressed_representation. As with almost any compression algorithm, the mapping from uncompressed_representation->compressed_representation is one->many and is up to the compression algorithm (not the format). The description of formulas is at the bottom.

I think maybe my original comment was misinterpreted.  I agree you cannot there are many possible compression algorithm choices that can map to this format.  What IMO what is missing here is a high level overview of what the data layout actually represents and defining the key terms used later in the document.  IIUC at a high level the algorithm is picking intervals of integers and using tAns to encode those intervals based using the probability estimate of integers observed in that range (i.e.) in this case interval ranges are the symbols for tANS).  Then to compress actual integers it is a combination of the integer range + an encoded offset.  But there is still a lot vocabulary to relate to how this works in practice (e.g. "tANS Weight" this is the estimated probability?, "4 way interleaved tAns Encode" = ?? neither linked tANS resource goes into tANS decoding", "bins = ranges", "latent variable" = encoded value?) which parts are delta encoded.    At a high-level why are multiple data chunks used.  This might be self-evident for people with compression algorithms, but from someone without much experience, I'm having a non-trivial time understanding the vocabulary, and I'm not seeing an overlap (might just be skimming too quickly) with the vocabulary used in the original tANS nor in the tutorial you wrote (which helped a lot gaining an intuitive understanding).

**Comment by emkornfield** [comment]
> I think for the most part it's actually a good thing; at least for data page, the two notions should overlap exactly between Parquet and Pcodec (or else the implementation is bad).

if we expect data header/metadata to not be stored within data pages, I think this is likely are much larger change with respect to parquet (e.g. we would need something akin to a dictionary page or re-use that concept).

**Comment by mwlon** [comment]
I agree that a detailed document about pcodec's approach (answering "why" questions) would be valuable. I might write up a white paper to this effect in the future, but I don't think it belongs in the format document. My intent with this document is not to explain things from first principles, but to make it possible for very motivated or expert people to (say) write their own pcodec implementation.

ANS can certainly be intimidating at first, but these sources definitely discuss decoding:
![Screenshot 2024-01-20 at 00 40 05](https://github.com/mwlon/pcodec/assets/6504033/d6c1439d-fd49-4382-a8af-5bb55021ae03)

4-way interleaving is just the `i % 4` thing in the doc. It improves performance.

I think some of your questions (e.g. "latent variable" = encoded value? and which parts are delta encoded) are already answered, though I suspect a different sort of doc would be most helpful to you. Unfortunately pcodec's high-level motivation docs are strewn in various places right now.
