### ISSUE TITLE
Is the data type encoded into the compressed buffer?

### ISSUE THREAD

**Issue by rabernat** [mwlon/pcodec#150]
The current Python interface requires the user to pass an existing Numpy array to decompress into, and it uses the dtype of that array to figure out which decompressor to dispatch, i.e.

https://github.com/mwlon/pcodec/blob/32eaddb384f216a4bbf34fb89d0a30c6cab21eb8/pco_python/src/lib.rs#L70-L79

I'm now working on implementing a Python function that allocates the numpy array from scratch, something like

```rust
fn auto_decompress<'py>(py: Python<'py>, compressed: &PyBytes) -> PyResult<PyArrayDyn>
```

However, I'm a bit stuck on how to determine the type of the resulting array (e..g. F32, I64, etc.) Assuming I have a buffer that has been compressed by pcodec, is this datatype somehow encoded into the header already? Or does pcodec always assume that the type is known a priori, from some out-of-band source of information?

**Comment by rabernat** [comment]
Answered my own question

https://github.com/mwlon/pcodec/blob/32eaddb384f216a4bbf34fb89d0a30c6cab21eb8/docs/format.md#standalone-format

The first byte of the chunks identifies the dtype

This is read here:

https://github.com/mwlon/pcodec/blob/32eaddb384f216a4bbf34fb89d0a30c6cab21eb8/pco/src/standalone/decompressor.rs#L126-L127

**Comment by mwlon** [comment]
Yep, you got it right. I don't have a public API for "peeking" the dtypes yet, but it's also not crazy to implement it outside the pco crate. For now one can read the first byte of the input data after the header (that is, `FileDecompressor::new(...)?.1[0]`).
