### ISSUE TITLE
Upper bound on compressed size

### ISSUE THREAD

**Issue by LDeakin** [mwlon/pcodec#161]
Many compression codecs have an upper bound on the size of the compressed output that can be computed based on the size of the input and the encoding parameters, but I didn't see an API providing this in `pcodec`. It would be valuable if `pcodec` had a function like this:
```rust
fn encoded_size_upper_bound<T: NumberLike>(nums_length: usize, config: &ChunkConfig) -> usize;
```

**Comment by mwlon** [comment]
Agreed. What we have right now are size hints (e.g. https://docs.rs/pco/latest/pco/standalone/struct.ChunkCompressor.html#implementations), but these

* aren't hard guarantees
* require doing most of the compression work first by instantiating a `ChunkCompressor` of some sort

**Comment by mwlon** [comment]
This is now implemented and will be released in the next version: https://github.com/mwlon/pcodec/pull/172

**Comment by mwlon** [comment]
For a whole standalone file, the worst case is pretty tight: ballpark `1.00001 * uncompressed_size + 16` at the moment (but don't rely on that formula).

**Comment by LDeakin** [comment]
Thanks @mwlon! This is a much-appreciated addition.
