### ISSUE TITLE
Miri is indicating undefined behaviour

### ISSUE THREAD

**Issue by LDeakin** [mwlon/pcodec#170]
Running pcodec through miri is indicating undefined behaviour in a few spots. Might be worth checking out.

---

OOB access in various tests here:
https://github.com/mwlon/pcodec/blob/0f91bef292b9a7422afe0d83b7b23efe577c6731/pco/src/bit_reader.rs#L17

---

Allocation here:
https://github.com/mwlon/pcodec/blob/0f91bef292b9a7422afe0d83b7b23efe577c6731/pco/src/standalone/decompressor.rs#L215-L218
leading to uninitialised memory access here: https://github.com/mwlon/pcodec/blob/0f91bef292b9a7422afe0d83b7b23efe577c6731/pco/src/delta.rs#L46

**Comment by mwlon** [comment]
Interesting, first I've heard of MIRI. We're not labeling some unsafe functions as such, which might be the problem. I think it's impossible for these to surface in the public API, but definitely something we should look into.

**Comment by mwlon** [comment]
MIRI is now satisfied on the main branch.

**Comment by LDeakin** [comment]
Great! I can confirm I'm no longer getting complaints from Miri about pcodec in my dependent crate
