### ISSUE TITLE
Infinite loop in approx_pair_gcd

### ISSUE THREAD

**Issue by mrmbernardi** [mwlon/pcodec#178]
https://github.com/mwlon/pcodec/blob/c01aefabbb5bfa175b3e3f127babdfcbdeadde1d/pco/src/float_mult_utils.rs#L116

This loop will continue forever if pair0 and pair1 start off too large. In that case one of them can become infinite, ratio becomes zero, and infinite times zero is NaN. At that point, all the conditions will be false forever and the loop will never terminate.

**Comment by mwlon** [comment]
Do you have a test case where it fails?

I'm not quite sure I buy the argument. The only way we might get to an infinity is through the `ratio * rhs.value` part of `lhs.value = (lhs.value - ratio * rhs.value).abs();`, but this is guaranteed to have absolute value less than `1.5 * rhs.value`, so I'm not sure it can cross the boundary from say `f32::MAX` to `f32::INFINITY`.

**Comment by mwlon** [comment]
Oh, TIL `f32::MAX + epsilon = f32::INFINITY`. Yeah I suppose this is possible.

**Comment by mwlon** [comment]
This has been fixed in https://github.com/mwlon/pcodec/pull/179
