### ISSUE TITLE
Benchmark vs. SPDP and PFor algorithms

### ISSUE THREAD

**Issue by rschu1ze** [mwlon/pcodec#189]
The benchmark page compares Pcode against Blosc and Zstd.

At least in the field of lossless floating-point compression, these seem to be the wrong algorithms to compare with, the ones in https://www.vldb.org/pvldb/vol17/p1418-tao.pdf seem much more relevant.

Similar algorithms exist for integers (https://arxiv.org/pdf/1209.2137), and it would be interesting to see how Pcode stacks up against these.

PS. We are in the process of adding Pcodec to ClickHouse, see https://github.com/ClickHouse/ClickHouse/pull/62823

**Comment by mwlon** [comment]
I agree those codecs are relevant, and I'd like to add some of them to my benchmark suite+results, but

* Pcodec does ints too; not just floats
* .zstd.parquet and blosc are two of the most common tools people use today, and the main things to compare against. The ones in this paper are much less well-known in the space of data engineering.

Exciting to hear that you're adding Pcodec to ClickHouse! I'll take a look.

**Comment by mwlon** [comment]
I took a closer look at the codecs used in these papers:

* SPDP (float) appears to be targeted at time series data and always does delta encoding, but might be interesting to compare against.
* bitshuffle (float) is essentially what Blosc does by default. I think you should just look at the existing benchmarks vs Blosc.
* fzip (float) is only for 2D and 3D arrays, and "is not suitable for compressing unstructured streams of floating-point numbers". It's kinda messed up that the paper compared against this one to begin with?
* chimp (float), like SPDP, looks like it's mainly for time series. It's implemented in Java, so it's impractical for me to build it into the benchmark command. I'd expect its compression ratio to be similar to SPDP, like the paper found.
* FastPFor (int) is something I should add. I expect it to be faster but substantially worse compression than Pco.
* TurboPFor (int) (not mentioned in those papers) is another thing to try.

With some bit manipulation, these last 2 can also be applied to floats. All in all, I think only SPDP and the PFor algorithms are realistic for now, so I'll change the issue title.

**Comment by pps83** [comment]
FastPFor/TurboPFor contain many different algorithms. I'd be shocked if pcodec does better compression than all available codecs in those two libs. I'd be absolutely floored if it does so faster.
Is there an easy way to test/compare pcodec on windows without anything rust on it? I'm interested in uint32_t compression only

**Comment by mwlon** [comment]
@pps83 I expect that on *most* datasets, Pco's default config will get better compression than PFor on *any* config. Of course, there will be exceptions if you look hard enough.

As I said, I doubt Pco will be quite as fast, but we'll see.

Yes it supports `u32`. That's visible in both the README and the docs.

> Is there an easy way to test/compare pcodec on windows without anything rust on it?

To answer what I think you're asking directly, the pip packages are pre-built and won't require any build tool. But I'd heavily interrogate this question. Is there a technical blocker preventing you from building Rust?

**Comment by pps83** [comment]
> Is there a technical blocker preventing you from building Rust?

I've never touched rust, don't have it on my pc, have no idea how to build anything. I see these only references how to test q_compress from c/c++: 
 - https://github.com/powturbo/TurboPFor-Integer-Compression/blob/06d6aad98b4be5471289f35d5d04fac4469cf6df/lib/icapp.c#L813 (windows code references q_compress_ffi.dll that I cannot find)
 - https://github.com/powturbo/TurboBench/tree/d68171773d7576c4323bb7966d01b7d4d2491b65/q_compress (linux only)

**Comment by mwlon** [comment]
There are also some rudimentary C bindings under pco_c/, but they're pretty limited and hard to use right now. If you might be interested in fleshing them out, contributions are certainly welcome.

**Comment by pps83** [comment]
I've built it using `cargo build --release` and took resulting q_compress_ffi.dll and used `auto_compress_i32` for testing.
I have two types of data (**data1** and **data2**) that I compress in large quantities. `q_compress_ffi` does give competitive compression ratios using level=9 compression. However, using tp4 I got better compression using many different codecs with much faster compression speed. In my case, I care for compression rate and decompression speed. With tp4 I got much faster decompression speeds. In some cases like 10x faster.

**data1** using q_compress_ffi compresses 10-20% worse with decoding speeds roughly 5-10x slower:
```
q_compress_ffi:
      size   ratio     E MB/s   D MB/s   function integer size=32 bits
    181844  45.34%      54.95   280.30   173:qcomp          quantile compress

tp4:
    149374  37.25%      47.41  1109.99   90:lztprle          Transpose +rle+zstd,12
    150821  37.61%      43.83  1560.19   81:Lztp   Byte      Transpose  +zstd,12
    161956  40.38%      68.19  2507.26   96:vlccomp          TurboVLC  +lz4,16

memcpy:
    401040 100.00%   38478.40 38345.63   120:memcpy           memcpy
```

**data2** using q_compress_ffi compresses 10% worse with decoding speeds roughly 5-40x slower:
```
q_compress_ffi:
      size   ratio     E MB/s   D MB/s   function integer size=32 bits
      2775  25.40%      26.17   241.58   173:qcomp            quantile compress

tp4:
      2447  22.40%      98.42  1561.28   86:Lztp4z Nibble    TransposeZ +zstd,12
      2514  23.01%    2603.43  7523.57   39:vszenc32         TurboVSimple zigzag
      2655  24.30%    2028.72  9538.88   11:p4nzenc128v32    TurboPFor128 zigzag

memcpy:
     10924 100.00%   81106.38 81127.09   120:memcpy           memcpy
```

I excluded some codecs that compress roughly like q_compress_ffi but with speeds over 10x (for example, data2 using p4nzenc128v32 encodes 75x faster, and decodes 40x faster while producing better compression). To be fair, there is overhead to call into a rust dll (to allocare/free buffers etc). So, compress should be better, but in real app I cannot avoid the overhead anyways.
On the other hand, turbopfor is worst code to deal with. I haven't spent with any 3rd party lib so much time debugging. It's horrible. FastPFor is much better in this regard.

**Comment by mwlon** [comment]
1. q_compress is no longer recommended. Use Pco.
2. We should really stop spamming this issue. If you have anything else of this nature to say, put it in the discord.

**Comment by mwlon** [comment]
... returning to the actual github issue here...

SPDP is now added into the benchmark suite. I created [Rust bindings to their official implementation](https://github.com/mwlon/spdp-sys/). The results do not look good for SPDP; here's the outcome (at SPDP level 5) on the Taxi dataset:

| codec | compression time | decompression time | size |
| pco              │ 5.518036083s │  859.055415ms │ 333004373 │
│ pco:level=5 │ 4.539319584s │  845.216418ms │ 348081054 │
│ spdp            │ 4.567133416s  │  5.006912291s  │ 1636214754 │

So Pco has much faster decompression and ~4.5x the compression ratio, given equal compression time. I tried some more datasets, and Pco outperforms to a similar degree.

PFors up next.

**Comment by mwlon** [comment]
I realized that FastPFor only supports x86 and hasn't been updated in a long time, so I won't be benchmarking against them. I might still try TurboPFor.

**Comment by mwlon** [comment]
Turbo PFor did a bit better. Extremely fast, as expected, but very bad compression: 3-5x larger than pco, just slightly better than SPDP.

I'm aware they have some way to layer with general purpose compressors, so that may be something to compare against later on. For now I'd consider this done though.

https://github.com/mwlon/pcodec/blob/main/docs/benchmark_results/mbp_m3_max.csv

**Comment by pps83** [comment]
> Extremely fast, as expected, but very bad compression: 3-5x larger than pco

[mbp_m3_max.csv](https://github.com/mwlon/pcodec/blob/main/docs/benchmark_results/mbp_m3_max.csv) lists tpfor. This gives little to no info what compression was used. zstd, for example, is one codec that has more than 10 compression levels. tpfor is collection of completely different algorithms and codecs that can be used for different types of input (i32, i64, f32, f64). Afaic it has more than 100 different coders/transformers, and on top of that, just like blosc, some are hybrid coders that use zstd/deflate/others under the hood. I would be absolutely floored if pco was able to do better than something from tpfor compression wise (3-5x is the result if one didn't use proper compressor from tpfor, or simply wanted to have misleading results).

**Comment by mwlon** [comment]
@pps83 The best way to compare more things is by adding configs here and trying them out: https://github.com/mwlon/pcodec/blob/main/pco_cli%2Fsrc%2Fbench%2Fcodecs%2Fturbo_pfor.rs

You can read the CLI docs / run the command to see how to benchmark any codec against any common file type. I'd love to see how Turbo PFor does with hand-tuned settings if you want to add more configs.

Parquet is probably the most used tabular data format on the planet in terms of #exabytes. It has good support in every language; just Google it.

**Comment by mwlon** [comment]
> I would be absolutely floored if pco was able to do better than something from tpfor compression wise.

I think you have mismatched expectations, but you should just try them out for yourself.

**Comment by pps83** [comment]
> @pps83 The best way to compare more things is by adding configs here and trying them out: https://github.com/mwlon/pcodec/blob/main/pco_cli%2Fsrc%2Fbench%2Fcodecs%2Fturbo_pfor.rs

I've never even tried rust, the only one time was just to build pcodec to be able to get that q_compress_ffi. And the only reason I came across to it was because it was [mentioned](https://github.com/powturbo/TurboPFor-Integer-Compression/blob/06d6aad98b4be5471289f35d5d04fac4469cf6df/lib/icapp.c#L813) as a possible codec to test/compare to inside turbopfor codebase.


> You can read the CLI docs / run the command to see how to benchmark any codec against any common file type. I'd love to see how Turbo PFor does with hand-tuned settings if you want to add more configs.


> Parquet is probably the most used tabular data format on the planet in terms of #exabytes. It has good support in every language; just Google it.

I did,

**Comment by pps83** [comment]
> @pps83 The best way to compare more things is by adding configs here and trying them out: https://github.com/mwlon/pcodec/blob/main/pco_cli%2Fsrc%2Fbench%2Fcodecs%2Fturbo_pfor.rs

I've never used rust, I touched it once only to build pcodec to be able to get that `q_compress_ffi.dll`. The only reason I came across to it was because it was [mentioned](https://github.com/powturbo/TurboPFor-Integer-Compression/blob/06d6aad98b4be5471289f35d5d04fac4469cf6df/lib/icapp.c#L813) as a possible codec to test/compare to inside turbopfor codebase.

I work with c++, and compression libs (I use a few libraries) are a small portion of my code. So to try/test anything, for it it has to be c++ only, or expose some sort of c/c++ interface (similar to q_compress_ffi).

TurboPFor/FastPFor encode arrays of numbers. In my case, I compress stock market data. For example:  open/high/low/close for [msft on 07/11/2024](https://www.nasdaq.com/market-activity/stocks/msft/historical?page=1&rows_per_page=25&timeline=m1) is: $462.98 $464.78 $451.55 $454.70. I compress it as [46298, 46478, 45155, 45470, .... days * 4 numbers]. In short, I compress 11KB of numbers is a single compress call. Here's sample uncompressed raw data that I compress: [SPY-2024-02-02-interleaved.bin](https://paste.c-net.org/SiobhanSorted).

No sure how that parquet is stored internally, but if it intermixes some numbers with unrelated numbers results wouldn't be amazing. Only if you interleave columns of similar data results would be good.

I see that cpcodec.dll exposes pco_simpler_compress / pco_simple_decompress (simple vs simper?), signatures are in [cpcodec_generated.h](https://github.com/mwlon/pcodec/blob/8f194324ae884f67727f9718d1674f9ed9c433b7/pco_c/include/cpcodec_generated.h).
Should I test these to compare pco vs tpfor? It would be better if pco exposed methods to compress **only** without mem management/allocation. E.g.  just like the input `{const void *nums, unsigned int len}` there could be output `{void *output, unsigned int size}` so that pco_simpler_compress would write directly to the provided output buffer without memory management.

**Comment by mwlon** [comment]
> I've never used rust, I touched it once only to build pcodec to be able to get that q_compress_ffi.dll...

As you gain experience software engineering, you'll probably learn that language is an (annoying, but) immaterial problem for natively compiled languages. I've contributed bindings for SPDP and [TurboPFor](https://docs.rs/turbo_pfor_sys/latest/turbo_pfor_sys/) into Rust, which is currently the easiest language to compare all these in. I think if you want to use a different language, that same level of effort is reasonable to expect. Fortunately there are already Pco C bindings to start from (though they aren't very good yet). Happy to review any improvements you make to them.

And again, Pcodec and Quantile Compression are different things. 

> I compress stock market data...

That sounds like a fine use case. The data sample is a bit small though; you'll get better compression if you have 10k+ numbers like it says in the README.

> No sure how that parquet is stored internally...

Another thing software engineers learn to do as they gain experience is search for publicly-answerable questions.

> Should I test these to compare pco vs tpfor? It would be better if pco exposed methods to compress only without mem management/allocation

These would be fine to compare with, and I agree about how the C bindings should be changed. Just remember to build with `--release`.

**Comment by pps83** [comment]
> As you gain experience software engineering ..

I know at least 5 different languages pretty well (and done professionally with 2-3 of these), but that's not the point. I've been doing c++ for 20+ years and that's the most comfortable language for me to work with. I do agree that learning a new language isn't a big deal once you know a few, but I'm happily retired in my 30-ies and don't think I need to learn new one for now :) I'm sure there are no limits on improving, by I'm now working in some other direction.

> That sounds like a fine use case. The data sample is a bit small though; you'll get better compression if you have 10k+ numbers like it says in the README.

I know, but that's the way it is. Most of my data is number of minutes in a day (when stock market is open) * ohlc (open/high/low/close) which ends up as 11KB uncompressed. I also have another format with seconds (that's 60 times larger in size).

> Another thing software engineers learn to do as they gain experience is search for publicly-answerable questions.

I've googled, looks like it does store data the way I do in my own code (by column instead of by row).

> These would be fine to compare with, and I agree about how the C bindings should be changed. Just remember to build with --release.

Yes, I use `cargo build --release`. Simply because mem management is part of the code pcodec results will not be fully representative. Anyways, I'll try later and post here how pco compares for my data.

**Comment by pps83** [comment]
Tables from [pervious post](https://github.com/mwlon/pcodec/issues/189#issuecomment-2134040014) with pco:

**data1** using q_compress_ffi compresses 10-20% worse with decoding speeds roughly 5-10x slower:
```
q_compress_ffi:
      size   ratio     E MB/s   D MB/s   function integer size=32 bits
    181844  45.34%      54.95   280.30   173:qcomp           quantile compress

tp4:
    149374  37.25%      47.41  1109.99   90:lztprle          Transpose +rle+zstd,12
    150821  37.61%      43.83  1560.19   81:Lztp   Byte      Transpose  +zstd,12
    161956  40.38%      68.19  2507.26   96:vlccomp          TurboVLC  +lz4,16

memcpy:
    401040 100.00%   38478.40 38345.63   120:memcpy           memcpy
```
**pco:**
```
    181758  45.32%      45.48  2236.24   175:pco             pco compress
```

**data2** using q_compress_ffi compresses 10% worse with decoding speeds roughly 5-40x slower:
```
q_compress_ffi:
      size   ratio     E MB/s   D MB/s   function integer size=32 bits
      2775  25.40%      26.17   241.58   173:qcomp           quantile compress

tp4:
      2447  22.40%      98.42  1561.28   86:Lztp4z Nibble    TransposeZ +zstd,12
      2514  23.01%    2603.43  7523.57   39:vszenc32         TurboVSimple zigzag
      2655  24.30%    2028.72  9538.88   11:p4nzenc128v32    TurboPFor128 zigzag

memcpy:
     10924 100.00%   81106.38 81127.09   120:memcpy           memcpy
```
**pco:**
```
      2704  24.75%       8.63  1030.05   175:pco             pco compress
```

So, yes, pco is much faster at decoding than q_compress. I used level=9 compression in both cases, and compression ratio is almost the same with q_compress, but decompression is speed is 5x-10x better (280.30 -> 2236.24 for **data1**, 241.58 -> 1030.05 for **data2**). Huge improvement. It's still slower than tpfor, but these numbers are **very good**. Top coders from [FastPFor](https://github.com/lemire/FastPFor) (it's like TurboPFor has many different coders) in my experience were worse at compression but faster at decompression. However, in tpfor with slightly worse compression I was always able to find coders that decompress much faster than FastPFor. Just like for **data2** p4nzenc128v32 compresses the same as pco, but more than 200x times faster, and decodes almost 10x faster.

**Comment by mwlon** [comment]
@pps83 Can you share the data samples?

**Comment by pps83** [comment]
> @pps83 Can you share the data samples?

https://paste.c-net.org/WarmsTight (zipped 3 files)

**Comment by mwlon** [comment]
The data was not passed in as intended. E.g. upon inspection, data2 is row-format, and when I split it into them (10 separate files, and I'm guessing `u32`) as Pco expects, we get `136944` bytes, significantly smaller than any of the numbers you reported for the hand-tuned TurboPFor configurations. I encourage you to replicate this on your end.

Giving the benefit of the doubt that you did read the README, I'll try to make the README clearer.

This issue has drifted a bit far from the original topic, so I'm going to lock it. If you have a more specific/researched issue or a small set (say up to 3) of TurboPFor configurations we should compare against, I'd be happy to hear about those in a separate issue.
