### ISSUE TITLE
Revise "choose mode" logic to accommodate another float mode

### ISSUE THREAD

**Issue by bzinberg** [mwlon/pcodec#194]
Tracking issue for the point raised by @mwlon in https://github.com/mwlon/pcodec/pull/193#discussion_r1609193001:

> Let's not touch this part yet. For now it will be impossible to choose Quantize mode, but that's ok.
> 
> When we do get to this, I think the logic will look more like
> ```
> match (fm_config, quantize_config) {
>   // one provided => return that
>   // both provided => error
>   // either enabled => do some common stuff, then maybe choose one or return classic
>   // disabled => classic
> }
> ```

[Currently](https://github.com/mwlon/pcodec/blob/ad6560b1b564b0619476aeee874fc067bddac868/pco/src/data_types/floats.rs#L7-L29), the logic is "Check whether using `FloatMult` looks promising.  If so, use it; otherwise, use `Classic`."  As of https://github.com/mwlon/pcodec/pull/193, there is a second float-specific mode, `FloatQuant`, and there will also be logic to guess whether using `FloatQuant` looks promising.  So the "either enabled" case in the above quote needs some way to weigh these two opinions against each other (or do its own separate logic).

**Comment by bzinberg** [comment]
Removed this draft of the `choose_mode` logic from https://github.com/mwlon/pcodec/pull/193 because we decided to save it for when this issue is addressed in full:
https://github.com/mwlon/pcodec/blob/15a06c4be18d9278800c7e4c98842893de7b862f/pco/src/float_quant_utils.rs#L48-L80

**Comment by bzinberg** [comment]
Now that https://github.com/mwlon/pcodec/pull/193/ is merged, I think it makes sense to clarify requirements and scope on this.  My current thoughts are:

* FloatQuant is really for the case where all or part of a dataset is exactly quantized, i.e., the `secondary` component is exactly zero for a significant portion of the dataset.
* That's why the logic I linked above in https://github.com/mwlon/pcodec/issues/194#issuecomment-2142684001 searches for the largest `k` for which 90% of the dataset is exactly quantized.  The 90% was arbitrary, can be changed.
* When both FloatMult and FloatQuant are enabled, we need a way to decide which one to use.  We of course don't want tons of "regressions" -- common use cases in which automatically choosing FloatQuant over FloatMult makes performance worse -- though shooting for absolutely no regressions on any dataset is also not feasible/useful.
* As a heuristic for deciding whether to use FloatMult or FloatQuant, I think it could be as simple as "if FloatQuant found a big enough `k`, assume the data is exactly quantized and use FloatQuant; otherwise use FloatMult"?  @mwlon, curious what you think here.

**Comment by mwlon** [comment]
Yes, I agree with most of that.

FloatQuant could also be useful if most of the numers are, say, 11 ULPs away from quantized, but I think that's unnatural, and we don't need to complicate this logic for that unlikely event.

When both Float modes are enabled, I think we should do something slightly more nuanced. I'm motivated by these hypothetical examples (and possible future unit tests)

* The numbers are random multiples of 2^-10 between 0.25 and 4.0. They're all perfectly quantizable by 8 bits, but then we spend unnecessary precision bits on the numbers between 0.5 and 4.0; better to use Mult mode.
* The numbers are random values between 0.25 and 4.0, quantized by 10 bits. We could express these as multiples of 2^-12, but that's again not optimal; better to use Quant mode.

Your heuristic is good, but I think we should decide on the float mode somewhat jointly. We can add it to `choose_candidate_base_by_trailing_zeros` fn in float_mult_utils.rs: estimate the number of bits saved on the sample by using each of FloatMult and FloatQuant, and if either is compelling enough, choose the better one. This function would require some reworking. Does that make sense?

**Comment by bzinberg** [comment]
Can you help me understand the first example?  I'm looking at a two-element dataset:

| number | binary `f32::to_latent_ordered()` form |
|--------|------------------------------|
| $0.25 + 2^{-10}$ | `1_01111101_00000001000000000000000` |
| $2.0 + 2^{-10}$ | `1_10000000_00000000001000000000000` |

FloatQuant would cut off the `k=12` trailing bits on each of those.  What would FloatMult do?

**Comment by mwlon** [comment]
Oh yeah I wrote some things wrong in that example. Amended.

**Comment by bzinberg** [comment]
I'd appreciate your help understanding the first example.  My understanding is that:

* FloatMult would choose the parameter $\texttt{base} = 2^{-10}$.
* Since the dataset consists of exact integer multiples of `base`, all the `secondary`s would be zero.
* The `primary`s would range from $2^8$ to $2^{12}$.  For example, if the two elements I posted above were in the dataset, their `primary`s would be $2^8 + 1$ and $2^{11} + 1$.
* The `primary`s for FloatQuant on that dataset would have a wider range, due in part to specifics of the bit layout of floats.

I think I need to know more about what happens to the `primary`s downstream to understand where the precision bits can be saved.  In the above, the width of the range doesn't matter yet because everything is a `u32`.  Where in the pipeline/codebase do the `primary`s get further compressed / potential savings get captured?

**Comment by mwlon** [comment]
We later check that the configuration is useful, and here we're almost enforcing that the quantization/multiplier is exact, so I think we should just assume

* Quant mode saves `k` bits per number
* Mult mode saves `PRECISION_BITS.sarurating_sub(exponent - base.log2())` (or something like that; AFK but there may be similar logic in this file already)

**Comment by mwlon** [comment]
In a bit more detail: the binning part of the algorithm tries to give each bin roughly equal weight (e.g. 1/256 of all the data by default). If each bin contains multiple `mult`s or multiple `quantums`, then we'll save the maximum possible number of bits I described above.

On the other hand, if some bins contain a single `mult` or `quantum`, then we can effectively "memorize" those parts of the distribution, making FloatMult or FloatQuant mode less compelling. But we check for this via `sampling::has_enough_infrequent_mults`, so we just need to make sure we're calling into that function properly later on.

**Comment by bzinberg** [comment]
Ah, that extra detail helps a lot, thanks.  What do the bins look like over the wire?  Is it:

```
Bin start value: u32 (or in general, L)
Offsets: stream of non-byte-aligned unsigned integers having width
         ceil(log2(next_bin.start - this_bin.start)) bits
```

**Comment by mwlon** [comment]
Everything is bit-packed. In each chunk of the file, there's a metadata section describing what all the `n_bins` bins are. The encoding is pretty simple: https://github.com/mwlon/pcodec/blob/main/docs/format.md#chunk-metadata. And then in the [real body of each chunk](https://github.com/mwlon/pcodec/blob/main/docs/format.md#data-page), each number is described by a [tANS-encoded symbol](https://graphallthethings.com/posts/streaming-ans-explained) from `[0, n_bins)` for which bin it's in, plus the offset bits for that bin.
