### ISSUE TITLE
Current rust bindings failing in pco_c

### ISSUE THREAD

**Issue by Dhananjay-Goel** [mwlon/pcodec#198]
How to use pcodec to compress data containing int arrays, unit64_t and uint8_t data type together in c?
Current rust bindings are failing in pco_c

P.S. Other compression algorithms for the same are also welcome.

**Comment by mwlon** [comment]
Pco just works on a single array at a time. You'd want to call into it once for each array.

What do you mean by "failing"?

**Comment by Dhananjay-Goel** [comment]
When taken a large array, it throws error while using pco_c

**Comment by mwlon** [comment]
What's the error?
