### ISSUE TITLE
Add missing options to `PyChunkConfig`

### ISSUE THREAD

**Issue by Skielex** [mwlon/pcodec#202]
Several options and properties are missing from `PyChunkConfig`. This includes:
- The `float_quant_spec` property.
- The `int_mult_spec` `Provided` option.
- The `float_mult_spec` `Provided` option.

I think updating `PyChunkConfig` to include all `ChunkConfig` options should be relatively simple. Should we do it?

**Comment by mwlon** [comment]
Yes, we should do it. Float quant will add Enabled in Rust land soon, but once all these things are in, we should release 0.2.0 (since it extends the format).

**Comment by Skielex** [comment]
Started work on this. Will submit PR soon.
