### ISSUE TITLE
Format Python files using a standard tool

### ISSUE THREAD

**Issue by Skielex** [mwlon/pcodec#205]
The Python files in the repo are not manually formatted. To ensure consistent styling we should use a common formatter such as `black` or `yapf` and define any custom style settings in `pyproject.toml`.

**Comment by Skielex** [comment]
@mwlon, do you have any preference the formatting tool apart from preferring 2-space indents? Personally, I've been happy with Black but it's strictly 4-space indents. Here are four of the popular formatters:
- [autopep8](https://github.com/hhatto/autopep8) - autopep8 automatically formats Python code to conform to the [PEP 8](https://www.python.org/dev/peps/pep-0008/) style guide. It uses the [pycodestyle](https://github.com/PyCQA/pycodestyle) utility to determine what parts of the code needs to be formatted. autopep8 is capable of fixing most of the formatting [issues](https://pycodestyle.readthedocs.org/en/latest/intro.html#error-codes) that can be reported by pycodestyle.
- [Black](https://black.readthedocs.io/en/stable/index.html) - By using Black, you agree to cede control over minutiae of hand-formatting. In return, Black gives you speed, determinism, and freedom from pycodestyle nagging about formatting. You will save time and mental energy for more important matters.
- [yapf](https://github.com/google/yapf) - YAPF is a Python formatter based on [clang-format](https://clang.llvm.org/docs/ClangFormat.html) (developed by Daniel Jasper). In essence, the algorithm takes the code and calculates the best formatting that conforms to the configured style. It takes away a lot of the drudgery of maintaining your code.
- [Ruff](https://docs.astral.sh/ruff/) - The Ruff formatter is an extremely fast Python code formatter designed as a drop-in replacement for [Black](https://pypi.org/project/black/), available as part of the ruff CLI via ruff format.

If you want 2-space indents I'd probably consider yapf or Ruff. Otherwise, I'd probably stick with Black.

**Comment by mwlon** [comment]
I've actually heard good things about Ruff. Would you be on board with it?

**Comment by Skielex** [comment]
Sure. Once the #203 is merged we can do a formatting PR with Ruff.

**Comment by bzinberg** [comment]
I personally use flake8 in most of my stuff, and personally prefer 4-space indents lol.  I'll be good with whatever you decide tho

**Comment by mwlon** [comment]
Yeah a couple people have expressed preference for that, and it's the default, so let's just use the default formatting. Though customizability and speed are pros regardless, so let's go with ruff.
