### ISSUE TITLE
`f32::log2` very slow on Windows

### ISSUE THREAD

**Issue by Skielex** [mwlon/pcodec#223]
For some reason the `f32::log2()` function, which is used a lot through `bin_cost` is very slow on Windows. I collected some data with Intel VTune running the following benchmark:
```
bench -i .\data\binary --input-format binary --codecs pco:level=8,pco:level=0 --iters 100 --dtypes f16,f32,f64
```
Here's a bottom-up view of the time spent in various functions:
![image](https://github.com/user-attachments/assets/27ad7b95-1432-4878-816e-fcee7fdd2ce1)

We can see that more than 8 seconds (14% of the total time) is spent in `fdlog`. By comparison, if we change from `f32::log2()` to `f32::log(2.0)`, which calls `logf` instead of `fdlog`, only about 0.7 second (1.4% of the total time) is spent getting the base-2 log.

Here's the bottom-up view when using `f32::log(2.0)` instead:
![image](https://github.com/user-attachments/assets/583b02ed-9d9e-4ccb-8512-77be5645cf6b)

The issue can be reproduced on my AMD 5900X and Intel 1370P, both running Windows 11. On Linux this doesn't not appear to be an issue.

I'm not sure what the best remedy is. We could simply replace `f32::log2()` with `f32::log(2.0)` for Windows.

**Comment by mwlon** [comment]
I tried out `.log(2.0)` on Mac, aarch64 with compression level 12 (where this hot loop is most hit), and it was 7% slower (`logf` vs `log2f` system calls). So yeah, unfortunately it makes sense to switch on OS.

Another more radical thing we could do is write our own (less precise) log2 function. Though I'd argue it's not worth the effort or complexity.

**Comment by Skielex** [comment]
If an approximate log2 function provides a meaningful performance improvement, I think it's probably worth it. At least if it's just a simple function with <50 lines of code.

For compression level 12 it looks like we can get a +10% reduction in time for `simple_compress` if we use an approximate log2 that's 2-3x faster than the current. However, I don't know if we can get one that's accurate enough and I don't know what the requirements for accuracy are.

**Comment by mwlon** [comment]
I think it's possible, and we might only need ~2-3 sig figs of precision (6-9 bits). It's used in bin optimization, where we decide which groups of adjacent bins to combine, based on estimated total bit cost. But whoever does this would need to think very carefully to ensure that the function:

* is monotonic
* doesn't give any confusing behavior where higher compression levels mistakenly optimize to be worse due to accumulated rounding errors
