### ISSUE TITLE
Testcase optimization

### ISSUE THREAD

**Issue by rachtsingh** [mwlon/pcodec#228]
No worries if this isn't the right forum, but I was thinking about adopting pcodec for compression of some of our timeseries data, and ran into a test case where zstd seems to perform better. Do you think this a usage issue (e.g. I need different options) or just that this data is not a good fit for pcodec?

Here's the output from `pcodec bench`:

```bash
$ pcodec bench --input pcodec_testcase.parquet --codecs pco:level=9,parquet:compression=zstd4
╭──────────┬───────────────────────────┬─────────────┬───────────────┬─────────────────╮
│ dataset  │ codec                     │ compress_dt │ decompress_dt │ compressed_size │
├──────────┼───────────────────────────┼─────────────┼───────────────┼─────────────────┤
│ i32_hour │ pco:level=9               │  3.047264ms │     434.267µs │              92 │
│ i32_hour │ parquet:compression=zstd4 │  3.228085ms │      37.575µs │             459 │
│ i64_idx  │ pco:level=9               │  2.489832ms │     723.768µs │             127 │
│ i64_idx  │ parquet:compression=zstd4 │  4.459501ms │     406.052µs │           87016 │
│ f64_y    │ pco:level=9               │ 10.862102ms │    1.778143ms │         1198460 │
│ f64_y    │ parquet:compression=zstd4 │ 14.918371ms │    1.196446ms │          770857 │
│ <sum>    │ pco:level=9               │ 16.399198ms │    2.936178ms │         1198679 │
│ <sum>    │ parquet:compression=zstd4 │ 22.605957ms │    1.640073ms │          858332 │
│ <sum>    │ <sum>                     │ 39.005155ms │    4.576251ms │         2057011 │
╰──────────┴───────────────────────────┴─────────────┴───────────────┴─────────────────╯
```

The thing we care about is the 770k column in zstd going to ~1.2mb.

Thanks!

**Comment by rachtsingh** [comment]
[testcase.zip](https://github.com/user-attachments/files/16397216/testcase.zip)

(didn't upload on first attempt).

**Comment by mwlon** [comment]
Hey, thanks for the dataset. Discord is the best place for specific cases like this, but Github issues are ok too.

If this is the data you're starting with, you're doing everything right. There's currently a weakness in Pco that I mean to address in the future to handle this.

Looking at the data, there's lots of stuff like this where is seems to switch between a few sequences:

```
-0.0009596579686649565
-0.0009596579686649565
-0.0009596579686649565
-0.0009596579686649565
-0.0016084844282154842
0.0
-0.0016084844282160116
-0.0016084844282160116
-0.0016084844282152483
```

and it keeps switching unpredictably between each of these (e.g. the -0.000959 sequence, the 0 sequence, and the -0.0016 sequence) and other later in the file. If your data comes in a more raw state, you could compress each of these sequences separately and probably get much better compression ratio.

I have a super rough plan for the fix here, but there are some unknowns so it may end up taking ~a few months. Or it could be much faster if things work out nicely.

**Comment by mwlon** [comment]
@rachtsingh I'm close to finishing some changes that will make handle this kinda of data better. Out of curiosity, how was this data generated?

**Comment by rachtsingh** [comment]
Hey, really great timing, we are running out of space 😅.

Let me email you details, happy to be a guinea pig.

**Comment by mwlon** [comment]
I've merged in a change that gets the `y` column down to 602kB by default.

I've also noticed that the heuristics are doing imperfectly and you can get down to 556kB if you additionally use FloatMult mode with `8.673617379884035e-19` (2**-60). I might look into that later too.

**Comment by mwlon** [comment]
Oh and if you additionally transpose it (sort by idx,hour instead of hour,idx), you can get down to 529kB.

**Comment by mwlon** [comment]
Both lookback delta encoding and the improved FloatQuant heuristics are released now.
