### ISSUE TITLE
logic bugs in q_compress rust crate

### ISSUE THREAD

**Issue by rnxpyke** [mwlon/pcodec#229]
I've been fuzzing a little project using q_compress in Rust, and managed to find some weird corner cases in the compressor/decompressor.

Minimal Reproduction Case:
```rust
#!/usr/bin/env -S cargo -Zscript
---
[dependencies]
q_compress = "0.11.7"
---

fn main() {
    use q_compress::{Compressor, Decompressor, DecompressorConfig, CompressorConfig};
    use std::io::Write;

    let a = f64::from_bits(0x8000000000004000);
    let b = f64::from_bits(0x8000000000000000);
    let cfg = CompressorConfig::default()
        .with_use_gcds(false)
        .with_delta_encoding_order(1)
        .with_compression_level(8);
    let mut compressor = Compressor::<f64>::from_config(cfg);
    let compressed = compressor.simple_compress(&[a, -a, b]);
    let mut decompressor: Decompressor<f64> = Decompressor::from_config(DecompressorConfig::default());
    decompressor.write_all(&compressed).unwrap();
    let decompressed = decompressor.simple_decompress().unwrap();
    assert_eq!(&[a, -a, b], decompressed.as_slice());
}
```

The above script tests a compress/decompress roundtrip using minimal input.
When run in debug mode, the code panics due to a "subtract with overflow" error in q_compress: 
`thread 'main' panicked at /home/crux/.cache/cargo/registry/src/index.crates.io-6f17d22bba15001f/q_compress-0.11.7/src/prefix.rs:89:29:
attempt to subtract with overflow`

running in release mode, all overflow checks are disabled.
the program still crashes at the `simple_decompress().unwrap()` call:
`called `Result::unwrap()` on an `Err` value: QCompressError { kind: Corruption, message: "expected the compressed body to contain 136 bits but instead processed 128" }`

**Comment by mwlon** [comment]
Cool, thanks for fuzzing and sharing those details!

q_compress has been succeeded by pco now, and it's highly recommended to switch. Pco does not express this particular issue, and the code is generally better written. Do you want to start fuzzing Pco instead, if you aren't already?

That said, I see the issue and will make a fix since I think there might still be a few q_compress users out there.

**Comment by rnxpyke** [comment]
I'll check out the pco apis, thanks
