### ISSUE TITLE
Problems with multichannel WAV files

### ISSUE THREAD

**Issue by Skielex** [mwlon/pcodec#230]
I tried compressing a stereo WAV file, which produced the error `invalid number of bytes per wav file sample`, even though the samples are 16-bit.

I think we should use `bits_per_sample` instead of `bytes_per_sample` in the `get_wav_field` function.

# Background
Header read in the `get_wav_field` function looks like this:
```
audio_format = 1
channel_count = 2
sampling_rate = 48000
bytes_per_second = 192000
bytes_per_sample = 4
bits_per_sample = 16
```
Notice `bytes_per_sample` and `bits_per_sample` values.

The data type is read from the header as:
``` rust
  let dtype = match header.bytes_per_sample {
    1 | 2 => Ok(DataType::Int16),
    3 => Ok(DataType::Int32),
    4 => Ok(DataType::Float32),
    _ => Err(anyhow!(
      "invalid number of bytes per wav file sample"
    )),
  }?;
```
While the `Header` field is named `bytes_per_sample`, it appears it should rather be named `bytes_per_block`. See header spec: https://en.wikipedia.org/wiki/WAV#WAV_file_header
```
   BytePerBloc     (2 bytes) : Number of bytes per block (NbrChannels * BitsPerSample / 8).
   BitsPerSample   (2 bytes) : Number of bits per sample
```

Changing the code to
``` rust
  let dtype = match header.bits_per_sample {
    8 | 16 => Ok(DataType::Int16),
    24 => Ok(DataType::Int32),
    32 => Ok(DataType::Float32),
    _ => Err(anyhow!(
      "invalid number of bits per wav file sample"
    )),
  }?;
```
allows `compress` to run without errors.

**Comment by mwlon** [comment]
Awesome, thanks for doing that investigation. Sounds like a simple fix - will you make a PR for it?
