### ISSUE TITLE
Streaming decompression

### ISSUE THREAD

**Issue by ccollie** [mwlon/pcodec#245]
Given the current architecture, is it possible to construct an iterator which returns values in a streaming fashion ?

**Comment by mwlon** [comment]
Yep! You can decompress a single batch of 256 numbers at a time using the low level API. Assuming you're using standalone, start from a FileDecompressor, obtain a [ChunkDecompressor](https://docs.rs/pco/latest/pco/standalone/struct.FileDecompressor.html#method.chunk_decompressor), then call [decompress](https://docs.rs/pco/latest/pco/standalone/struct.ChunkDecompressor.html#method.decompress) with a `dst` of size 256. You could buffer over that to get true value-by-value iteration.

**Comment by ccollie** [comment]
Nice ! I'm using this in a library to store time series samples in fixed size chunks, and i want to extract ranges without having to allocate memory for all the compressed samples.
