### ISSUE TITLE
Support `u8`/`i8`?

### ISSUE THREAD

**Issue by BartMassey** [mwlon/pcodec#33]
Code support all Rust native numeric types except `u8`/`i8` right now. I don't have a use case for these yet, but I can imagine someone doing so in the future: this is a placeholder issue for that situation for now.

Downsides of adding this support are a bit more code with a bit more maintenance, and perhaps a bit more confusion about what this compressor is intended for — not for data that isn't in some sense "time series".

**Comment by mwlon** [comment]
For more depth on why the current plan is not to add them:

1. Adding more `NumberLike`s requires more maintenance in downstream code. For example, adding a few dtypes incurred this PR to the CLI: https://github.com/mwlon/quantile-compression/pull/34. There are also other connectors in other languages like https://github.com/pancake-db/pancake-scala-client/blob/main/src/main/scala/com/pancakedb/client/NativeCore.scala that will need more boilerplate code added.
2. Supporting a `u8` type could confuse people into trying q_compress on binary or text-like data, which it is not meant to do. 
3. [Downstream users can already convert to and from bigger ints, or even make their own data types.](https://github.com/mwlon/quantile-compression#custom-data-types)
4. There are sooo many other data types we could add that would actually improve compression ratio for or enable niche use cases. `u256`, `f8`, `TimestampMillis`, `Date`. Let's add those ones on an as-needed basis.

**Comment by mwlon** [comment]
Issue with more up-to-date thoughts: https://github.com/mwlon/pcodec/issues/262
